"""
python-bluebutton
FILE: file_def_cms
Created: 3/6/15 10:42 PM

Add Seg List for definition of CMS BlueButton file

"""
__author__ = 'Mark Scrimshire:@ekivemark'

# Seg is used to control and translate headings and lines
SEG_DEF = [
    {"match": "mymedicare.GovPersonalHealthInformation",
        "pre": {"title": "MyMedicare.gov Personal Health Information",
                "languageCode": "code=\"en-US\"", "versionNumber": {"value": "3"},
                "effectiveTime": {"value": "20150210171504+0500"},
                "confidentialityCode": {"code": "N",
                                        "codeSystem": "2.16.840.1.113883.5.25"},
                "comments": [],
                "originator": "MyMedicare.gov",
                "source": "MyMedicare.gov",
                },
        "level": 0,
        "name": "header",
        "type": "dict", "dict_name": "header", "multi": "False",
        "parent": "",
        "file_source": "CMS",
     },
    {"match": "demographic",
     "level": 0,
     "name": "patient",
     "type": "dict", "dict_name": "patient", "multi": "False",
     "mode": "",
     "parent": "",
     "file_source": "CMS",
     },
    {"match": "patient.partAEffectiveDate",
     "level": 1,
     "name": "medicare",
     "type": "dict", "dict_name": "medicare", "multi": "False",
     "parent": "demographic",
     "file_source": "CMS",
     },
    {"match": "patient.partBEffectiveDate",
     "level": 1,
     "name": "medicare",
     "type": "dict", "dict_name": "medicare", "multi": "False",
     "parent": "demographic",
     "file_source": "CMS",
     },
    {"match": "patient.phoneNumber",
     "level": 2,
     "name": "phoneNumber",
     "type": "list", "sub_type": "string", "multi": "True",
     "mode": "",
     "parent": "demographic",
     "file_source": "CMS",
     },
    {"match": "emergencyContact",
     "level": 0,
     "name": "emergencyContact",
     "type": "list", "sub_type": "dict", "multi": "True",
     "mode": "",
     "parent": "",
     "file_source": "CMS",
     },
    {"match": "emergencyContact.contactName",
     "level": 1,
     "list": True,
     "name": "contactName",
     "type": "dict", "dict_name": "contactName", "multi": "True",
     "mode": "block",
     "parent": "emergencyContact",
     "file_source": "CMS",
     },
    {"match": "emergencyContact.homePhone",
     "level": 2,
     "type": "dict", "dict_name": "phone", "multi": "True",
     "mode": "block",
     "name": "home",
     "field": "home",
     "parent": "emergencyContact",
     "file_source": "CMS",
     },
    {"match": "emergencyContact.workPhone",
     "level": 2,
     "type": "dict", "dict_name": "phone", "multi": "True",
     "mode": "block",
     "name": "work",
     "field": "work",
     "parent": "emergencyContact",
     "file_source": "CMS",
     },
    {"match": "emergencyContact.mobilePhone",
     "level": 2,
     "type": "dict", "dict_name": "phone", "multi": "True",
     "mode": "block",
     "name": "mobile",
     "field": "mobile",
     "parent": "emergencyContact",
     "file_source": "CMS",
     },
    {"match": "selfReportedMedicalConditions",
     "name": "medicalConditions",
     "level": 0,
     "type": "list", "sub_type": "dict", "multi": "True",},
    {"match": "selfReportedAllergies",
     "name": "Allergies",
     "level": 0,
     "type": "list", "sub_type": "dict", "multi": "True",},
    {"match": "selfReportedImplantableDevice",
     "name": "ImplantableDevices",
     "level": 0,
     "type": "list", "sub_type": "dict", "multi": "True",},
    {"match": "selfReportedImmunizations",
     "name": "Immunizations",
     "level": 0,
     "type": "list", "sub_type": "dict", "multi": "True",},

    {"match": "selfReportedLabsAndTests",
     "name": "Labs",
     "level": 0,
     "type": "list", "sub_type": "dict", "multi": "True",},
    {"match": "selfReportedVitalStatistics",
     "name": "vitals",
     "level": 0,
     "type": "list", "sub_type": "dict", "multi": "True"},
    {"match": "familyMedicalHistory",
     "name": "familyHistory",
     "level": 0,
     "type": "list", "sub_type": "dict", "multi": "True"},
    {"match": "drugs",
     "name": "medications",
     "level": 0,
     "type": "list", "sub_type": "dict", "multi": "True"},
    {"match": "preventiveServices",
     "name": "preventiveServices",
     "level": 0,
     "type": "list", "sub_type": "dict", "multi": "True"},
    {"match": "providers",
     "name": "providers",
     "level": 0,
     "type": "list", "sub_type": "dict", "multi": "True"},
    {"match": "pharmacies",
     "name": "pharmacies",
     "level": 0,
     "type": "list", "sub_type": "dict", "multi": "True",},
    {"match": "pharmacyName",
     "name": "pharmacyName",
     "level": 0,
     "type": "dict", "sub_type": "dict", "multi": "True",},
    {"match": "plans",
     "name": "insurance",
     "level": 0,
     "type": "list", "sub_type": "dict", "multi": "True",},
    {"match": "employerSubsidy",
     "name": "category",
     "level": 1,
     "type": "dict",},
    {"match": "primaryInsurance",
     "name": "category",
     "level": 1,
     "type": "dict",},
    {"match": "otherInsurance",
     "name": "category",
     "level": 1,
     "type": "dict", "multi": "True",},
    {"match": "claimSummary",
     "name": "claims",
     "level": 0,
     "type": "list", "sub_type": "dict", "multi": "True",},
    {"match": "claimHeader",
     "name": "claim",
     "level": 1,
     "type": "list", "sub_type": "dict", "multi": "True",},
    {"match": "claimLinesForClaimNumber",
     "name": "details",
     "level": 2,
     "type": "list", "sub_type": "dict","multi": "True",},
    ]