"""
python-bluebutton
FILE: file_def_cms
Created: 3/6/15 10:42 PM

Add Seg List for definition of CMS BlueButton file

"""
__author__ = 'Mark Scrimshire:@ekivemark'

# Seg is used to control and translate headings and lines
SEG_DEF = [{"match": "mymedicare.GovPersonalHealthInformation",
        "pre": {"title": "MyMedicare.gov Personal Health Information",
            "languageCode": "code=\"en-US\"", "versionNumber": {"value": "3"},
            "effectiveTime": {"value": "20150210171504+0500"},
            "confidentialityCode": {"code": "N", "codeSystem": "2.16.840.1.113883.5.25"},
            "originator": "MyMedicare.gov"},
        "level": 0,
        "name": "header",
        "this_entry": "",
        "content": "dict",
        "multi": "False",
        "parent": "",
        "file_source": "CMS",
        },
    {"match": "demographic",
     "pre": {},
     "level": 0,
     "name": "patient",
     "content": "dict",
     "mode": "",
     "multi": "False",
     "parent": "",
     "file_source": "CMS",
     },
    {"match": "emergencyContact",
     "pre": {},
     "level": 0,
     "name": "emergencyContact",
     "type": "list",
     "mode": "",
     "multi": "True",
     "parent": "",
     "file_source": "CMS",
    },
    {"match": "emergencyContact.contactName",
     "pre": {},
     "level": 1,
     "list": True,
     "name": "name",
     "end_match": "emailAddress",
     "type": "dict",
     "mode": "block",
     "dict_name": "",
     "multi": "False",
     "parent": "emergencyContact",
     "file_source": "CMS",
     },
    {"match": "emergencyContact.addressType",
     "pre": {},
     "level": 2,
     "type": "dict",
     "mode": "block",
     "dict_name": "address",
     "multi": "False",
     "name": "type",
     "end_match": "zip",
     "parent": "emergencyContact",
     "file_source": "CMS",
     },
    {"match": "emergencyContact.addressLine1",
     "pre": {},
     "level": 2,
     "type": "dict",
     "mode": "block",
     "dict_name": "address",
     "multi": "False",
     "name": "line1",
     "end_match": "zip",
     "parent": "emergencyContact",
     "file_source": "CMS",
     },
    {"match": "emergencyContact.addressLine2",
     "pre": {},
     "level": 2,
     "type": "dict",
     "mode": "block",
     "dict_name": "address",
     "multi": "False",
     "name": "line2",
     "end_match": "zip",
     "parent": "emergencyContact",
     "file_source": "CMS",
     },
    {"match": "emergencyContact.city",
     "pre": {},
     "level": 2,
     "type": "dict",
     "mode": "block",
     "dict_name": "address",
     "multi": "False",
     "name": "city",
     "end_match": "zip",
     "parent": "emergencyContact",
     "file_source": "CMS",
     },
    {"match": "emergencyContact.state",
     "pre": {},
     "level": 2,
     "type": "dict",
     "mode": "block",
     "dict_name": "address",
     "multi": "False",
     "name": "state",
     "end_match": "zip",
     "parent": "emergencyContact",
     "file_source": "CMS",
     },
    {"match": "emergencyContact.zip",
     "pre": {},
     "level": 2,
     "type": "dict",
     "mode": "close",
     "dict_name": "address",
     "multi": "False",
     "name": "zip",
     "end_match": "zip",
     "parent": "emergencyContact",
     "file_source": "CMS",
     },
    {"match": "emergencyContact.homePhone",
     "pre": {},
     "level": 2,
     "type": "dict",
     "dict_name": "phone",
     "mode": "block",
     "multi": "False",
     "name": "home",
     "field": "home",
     "end_match": "mobilePhone",
     "parent": "emergencyContact",
     "file_source": "CMS",
     },
    {"match": "emergencyContact.workPhone",
     "pre": {},
     "level": 2,
     "type": "dict",
     "dict_name": "phone",
     "mode": "block",
     "multi": "False",
     "name": "work",
     "field": "work",
     "end_match": "mobilePhone",
     "parent": "emergencyContact",
     "file_source": "CMS",
     },
    {"match": "emergencyContact.mobilePhone",
     "pre": {},
     "level": 2,
     "type": "dict",
     "dict_name": "phone",
     "mode": "close",
     "multi": "False",
     "name": "mobile",
     "field": "mobile",
     "end_match": "mobilePhone",
     "parent": "emergencyContact",
     "file_source": "CMS",
     },

    {"match": "selfReportedMedicalConditions", "name": "medicalConditions"},
    {"match": "selfReportedAllergies", "name": "Allergies"},
    {"match": "selfReportedImplantableDevice", "name": "ImplantableDevices"},
    {"match": "selfReportedImmunizations", "name": "Immunizations"},
    {"match": "selfReportedLabsAndTests", "name": "Labs"},
    {"match": "selfReportedVitalStatistics", "name": "vitals"},
    {"match": "familyMedicalHistory", "name": "familyHistory"},
    {"match": "drugs", "name": "medications"},
    {"match": "preventiveServices", "name": "preventiveServices"},
    {"match": "providers", "name": "providers"},
    {"match": "pharmacies", "name": "pharmacies"},
    {"match": "plans", "name": "insurance", "type": "list"},
    {"match": "employerSubsidy", "name": "category", "level": 1},
    {"match": "primaryInsurance", "name": "category", "level": 1},
    {"match": "otherInsurance", "name": "category", "level": 1},
    {"match": "claimSummary", "name": "claims", "type": "list",
     "level": 0},
    {"match": "claimHeader", "name": "claim", "type": "dict",
     "level": 1},
    {"match": "claimLinesForClaimNumber", "name": "details",
     "type": "list", "level": 2, "multi": "True"},
    ]